In [1]:
import pandas as pd
import numpy as np

### Pandas Data Structures

In [2]:
pd.DataFrame({'yes':[50, 21], 'No':[131, 2]})

   yes   No
0   50  131
1   21    2

In [4]:
test = pd.read_csv("https://www.dropbox.com/s/0mnday26niaqc6i/test.csv?dl=1")

In [6]:
test.head(2)

,key,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
0,2015-01-27 13:08:24.0000002,2015-01-27 13:08:24 UTC,-73.973320,40.763805,-73.981430,40.743835,1
1,2015-01-27 13:08:24.0000003,2015-01-27 13:08:24 UTC,-73.986862,40.719383,-73.998886,40.739201,1

In [8]:
test.shape

(9914, 7)

In [10]:
test = pd.read_csv("https://www.dropbox.com/s/0mnday26niaqc6i/test.csv?dl=1", index_col = 0)

In [11]:
test.head(3)

,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
key,,,,,,
2015-01-27 13:08:24.0000002,2015-01-27 13:08:24 UTC,-73.973320,40.763805,-73.981430,40.743835,1
2015-01-27 13:08:24.0000003,2015-01-27 13:08:24 UTC,-73.986862,40.719383,-73.998886,40.739201,1
2011-10-08 11:53:44.0000002,2011-10-08 11:53:44 UTC,-73.982524,40.751260,-73.979654,40.746139,1

In [12]:
test.pickup_datetime

key
2015-01-27 13:08:24.0000002      2015-01-27 13:08:24 UTC
2015-01-27 13:08:24.0000003      2015-01-27 13:08:24 UTC
2011-10-08 11:53:44.0000002      2011-10-08 11:53:44 UTC
2012-12-01 21:12:12.0000002      2012-12-01 21:12:12 UTC
2012-12-01 21:12:12.0000003      2012-12-01 21:12:12 UTC
2012-12-01 21:12:12.0000005      2012-12-01 21:12:12 UTC
2011-10-06 12:10:20.0000001      2011-10-06 12:10:20 UTC
2011-10-06 12:10:20.0000003      2011-10-06 12:10:20 UTC
2011-10-06 12:10:20.0000002      2011-10-06 12:10:20 UTC
2014-02-18 15:22:20.0000002      2014-02-18 15:22:20 UTC
2014-02-18 15:22:20.0000003      2014-02-18 15:22:20 UTC
2014-02-18 15:22:20.0000001      2014-02-18 15:22:20 UTC
2010-03-29 20:20:32.0000002      2010-03-29 20:20:32 UTC
2010-03-29 20:20:32.0000001      2010-03-29 20:20:32 UTC
2011-10-06 03:59:12.0000002      2011-10-06 03:59:12 UTC
2011-10-06 03:59:12.0000001      2011-10-06 03:59:12 UTC
2012-07-15 16:45:04.0000006      2012-07-15 16:45:04 UTC
2012-07-15 16:45:04.0000002      2012-07-15 16:45:04 UTC
2012-07-15 16:45:04.0000003      2012-07-15 16:45:04 UTC
2012-07-15 16:45:04.0000004      2012-07-15 16:45:04 UTC
2014-10-29 02:09:56.0000001      2014-10-29 02:09:56 UTC
2014-06-14 13:39:00.00000010     2014-06-14 13:39:00 UTC
2014-06-14 13:39:00.00000060     2014-06-14 13:39:00 UTC
2014-06-14 13:39:00.00000087     2014-06-14 13:39:00 UTC
2014-06-14 13:39:00.00000050     2014-06-14 13:39:00 UTC
2014-06-14 13:39:00.0000003      2014-06-14 13:39:00 UTC
2014-06-14 13:39:00.000000158    2014-06-14 13:39:00 UTC
2014-06-14 13:39:00.00000015     2014-06-14 13:39:00 UTC
2014-06-14 13:39:00.00000073     2014-06-14 13:39:00 UTC
2014-06-14 13:39:00.00000077     2014-06-14 13:39:00 UTC
                                          ...
2013-09-25 22:00:00.00000060     2013-09-25 22:00:00 UTC
2013-09-25 22:00:00.000000213    2013-09-25 22:00:00 UTC
2013-09-25 22:00:00.000000150    2013-09-25 22:00:00 UTC
2013-09-25 22:00:00.00000010     2013-09-25 22:00:00 UTC
2013-09-25 22:00:00.000000146    2013-09-25 22:00:00 UTC
2013-09-25 22:00:00.00000041     2013-09-25 22:00:00 UTC
2013-09-25 22:00:00.000000109    2013-09-25 22:00:00 UTC
2013-09-25 22:00:00.000000210    2013-09-25 22:00:00 UTC
2013-09-25 22:00:00.000000151    2013-09-25 22:00:00 UTC
2013-09-25 22:00:00.000000190    2013-09-25 22:00:00 UTC
2013-09-25 22:00:00.000000153    2013-09-25 22:00:00 UTC
2013-09-25 22:00:00.000000241    2013-09-25 22:00:00 UTC
2013-09-25 22:00:00.000000127    2013-09-25 22:00:00 UTC
2015-02-20 11:08:29.0000001      2015-02-20 11:08:29 UTC
2015-01-12 15:36:37.0000002      2015-01-12 15:36:37 UTC
2015-06-07 00:38:14.0000002      2015-06-07 00:38:14 UTC
2015-04-12 21:56:22.0000005      2015-04-12 21:56:22 UTC
2015-04-10 11:56:54.0000004      2015-04-10 11:56:54 UTC
2015-06-25 01:01:46.0000002      2015-06-25 01:01:46 UTC
2015-05-29 10:02:42.0000001      2015-05-29 10:02:42 UTC
2015-06-30 20:03:50.0000002      2015-06-30 20:03:50 UTC
2015-02-27 19:36:02.0000006      2015-02-27 19:36:02 UTC
2015-06-15 01:00:06.0000002      2015-06-15 01:00:06 UTC
2015-02-03 09:00:58.0000001      2015-02-03 09:00:58 UTC
2015-05-19 13:58:11.0000001      2015-05-19 13:58:11 UTC
2015-05-10 12:37:51.0000002      2015-05-10 12:37:51 UTC
2015-01-12 17:05:51.0000001      2015-01-12 17:05:51 UTC
2015-04-19 20:44:15.0000001      2015-04-19 20:44:15 UTC
2015-01-31 01:05:19.0000005      2015-01-31 01:05:19 UTC
2015-01-18 14:06:23.0000006      2015-01-18 14:06:23 UTC
Name: pickup_datetime, Length: 9914, dtype: object

In [13]:
test['pickup_datetime']

key
2015-01-27 13:08:24.0000002      2015-01-27 13:08:24 UTC
2015-01-27 13:08:24.0000003      2015-01-27 13:08:24 UTC
2011-10-08 11:53:44.0000002      2011-10-08 11:53:44 UTC
2012-12-01 21:12:12.0000002      2012-12-01 21:12:12 UTC
2012-12-01 21:12:12.0000003      2012-12-01 21:12:12 UTC
2012-12-01 21:12:12.0000005      2012-12-01 21:12:12 UTC
2011-10-06 12:10:20.0000001      2011-10-06 12:10:20 UTC
2011-10-06 12:10:20.0000003      2011-10-06 12:10:20 UTC
2011-10-06 12:10:20.0000002      2011-10-06 12:10:20 UTC
2014-02-18 15:22:20.0000002      2014-02-18 15:22:20 UTC
2014-02-18 15:22:20.0000003      2014-02-18 15:22:20 UTC
2014-02-18 15:22:20.0000001      2014-02-18 15:22:20 UTC
2010-03-29 20:20:32.0000002      2010-03-29 20:20:32 UTC
2010-03-29 20:20:32.0000001      2010-03-29 20:20:32 UTC
2011-10-06 03:59:12.0000002      2011-10-06 03:59:12 UTC
2011-10-06 03:59:12.0000001      2011-10-06 03:59:12 UTC
2012-07-15 16:45:04.0000006      2012-07-15 16:45:04 UTC
2012-07-15 16:45:04.0000002      2012-07-15 16:45:04 UTC
2012-07-15 16:45:04.0000003      2012-07-15 16:45:04 UTC
2012-07-15 16:45:04.0000004      2012-07-15 16:45:04 UTC
2014-10-29 02:09:56.0000001      2014-10-29 02:09:56 UTC
2014-06-14 13:39:00.00000010     2014-06-14 13:39:00 UTC
2014-06-14 13:39:00.00000060     2014-06-14 13:39:00 UTC
2014-06-14 13:39:00.00000087     2014-06-14 13:39:00 UTC
2014-06-14 13:39:00.00000050     2014-06-14 13:39:00 UTC
2014-06-14 13:39:00.0000003      2014-06-14 13:39:00 UTC
2014-06-14 13:39:00.000000158    2014-06-14 13:39:00 UTC
2014-06-14 13:39:00.00000015     2014-06-14 13:39:00 UTC
2014-06-14 13:39:00.00000073     2014-06-14 13:39:00 UTC
2014-06-14 13:39:00.00000077     2014-06-14 13:39:00 UTC
                                          ...
2013-09-25 22:00:00.00000060     2013-09-25 22:00:00 UTC
2013-09-25 22:00:00.000000213    2013-09-25 22:00:00 UTC
2013-09-25 22:00:00.000000150    2013-09-25 22:00:00 UTC
2013-09-25 22:00:00.00000010     2013-09-25 22:00:00 UTC
2013-09-25 22:00:00.000000146    2013-09-25 22:00:00 UTC
2013-09-25 22:00:00.00000041     2013-09-25 22:00:00 UTC
2013-09-25 22:00:00.000000109    2013-09-25 22:00:00 UTC
2013-09-25 22:00:00.000000210    2013-09-25 22:00:00 UTC
2013-09-25 22:00:00.000000151    2013-09-25 22:00:00 UTC
2013-09-25 22:00:00.000000190    2013-09-25 22:00:00 UTC
2013-09-25 22:00:00.000000153    2013-09-25 22:00:00 UTC
2013-09-25 22:00:00.000000241    2013-09-25 22:00:00 UTC
2013-09-25 22:00:00.000000127    2013-09-25 22:00:00 UTC
2015-02-20 11:08:29.0000001      2015-02-20 11:08:29 UTC
2015-01-12 15:36:37.0000002      2015-01-12 15:36:37 UTC
2015-06-07 00:38:14.0000002      2015-06-07 00:38:14 UTC
2015-04-12 21:56:22.0000005      2015-04-12 21:56:22 UTC
2015-04-10 11:56:54.0000004      2015-04-10 11:56:54 UTC
2015-06-25 01:01:46.0000002      2015-06-25 01:01:46 UTC
2015-05-29 10:02:42.0000001      2015-05-29 10:02:42 UTC
2015-06-30 20:03:50.0000002      2015-06-30 20:03:50 UTC
2015-02-27 19:36:02.0000006      2015-02-27 19:36:02 UTC
2015-06-15 01:00:06.0000002      2015-06-15 01:00:06 UTC
2015-02-03 09:00:58.0000001      2015-02-03 09:00:58 UTC
2015-05-19 13:58:11.0000001      2015-05-19 13:58:11 UTC
2015-05-10 12:37:51.0000002      2015-05-10 12:37:51 UTC
2015-01-12 17:05:51.0000001      2015-01-12 17:05:51 UTC
2015-04-19 20:44:15.0000001      2015-04-19 20:44:15 UTC
2015-01-31 01:05:19.0000005      2015-01-31 01:05:19 UTC
2015-01-18 14:06:23.0000006      2015-01-18 14:06:23 UTC
Name: pickup_datetime, Length: 9914, dtype: object

In [14]:
test.iloc[0]

pickup_datetime      2015-01-27 13:08:24 UTC
pickup_longitude                    -73.9733
pickup_latitude                      40.7638
dropoff_longitude                   -73.9814
dropoff_latitude                     40.7438
passenger_count                            1
Name: 2015-01-27 13:08:24.0000002, dtype: object

In [15]:
test.iloc[1]

pickup_datetime      2015-01-27 13:08:24 UTC
pickup_longitude                    -73.9869
pickup_latitude                      40.7194
dropoff_longitude                   -73.9989
dropoff_latitude                     40.7392
passenger_count                            1
Name: 2015-01-27 13:08:24.0000003, dtype: object

In [16]:
test.iloc[0:3, 0]

key
2015-01-27 13:08:24.0000002    2015-01-27 13:08:24 UTC
2015-01-27 13:08:24.0000003    2015-01-27 13:08:24 UTC
2011-10-08 11:53:44.0000002    2011-10-08 11:53:44 UTC
Name: pickup_datetime, dtype: object

In [17]:
test.iloc[-5]

pickup_datetime      2015-05-10 12:37:51 UTC
pickup_longitude                    -73.9681
pickup_latitude                       40.797
dropoff_longitude                   -73.9556
dropoff_latitude                     40.7804
passenger_count                            6
Name: 2015-05-10 12:37:51.0000002, dtype: object

### Labe Base Selection

In [19]:
test = pd.read_csv("https://www.dropbox.com/s/0mnday26niaqc6i/test.csv?dl=1")
test.loc[0, 'pickup_datetime']

'2015-01-27 13:08:24 UTC'

In [20]:
test.loc[:5, ['pickup_datetime', 'pickup_latitude', 'dropoff_latitude']]

           pickup_datetime  pickup_latitude  dropoff_latitude
0  2015-01-27 13:08:24 UTC        40.763805         40.743835
1  2015-01-27 13:08:24 UTC        40.719383         40.739201
2  2011-10-08 11:53:44 UTC        40.751260         40.746139
3  2012-12-01 21:12:12 UTC        40.767807         40.751635
4  2012-12-01 21:12:12 UTC        40.789775         40.744427
5  2012-12-01 21:12:12 UTC        40.765547         40.740053

In [23]:
test.loc[1, 'pickup_latitude']

40.719383239746094

In [24]:
test['pickup_latitude']

0       40.763805
1       40.719383
2       40.751260
3       40.767807
4       40.789775
5       40.765547
6       40.773204
7       40.646636
8       40.709638
9       40.765519
10      40.741973
11      40.740893
12      40.739937
13      40.762723
14      40.728701
15      40.746993
16      40.731721
17      40.785598
18      40.763349
19      40.756025
20      40.705866
21      40.764702
22      40.736360
23      40.748480
24      40.759992
25      40.757450
26      40.773722
27      40.733877
28      40.778705
29      40.743432
          ...
9884    40.643817
9885    40.722762
9886    40.752837
9887    40.783282
9888    40.767512
9889    40.714675
9890    40.754152
9891    40.760505
9892    40.757770
9893    40.796197
9894    40.730415
9895    40.731167
9896    40.776862
9897    40.805538
9898    40.777515
9899    40.764874
9900    40.772480
9901    40.762753
9902    40.752655
9903    40.738731
9904    40.645035
9905    40.767406
9906    40.720776
9907    40.769611
9908    40.718922
9909    40.796997
9910    40.803600
9911    40.726608
9912    40.735432
9913    40.754070
Name: pickup_latitude, Length: 9914, dtype: float64

In [25]:
test.groupby('passenger_count').count()

,key,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude
passenger_count,,,,,,
1,6914,6914,6914,6914,6914,6914
2,1474,1474,1474,1474,1474,1474
3,447,447,447,447,447,447
4,206,206,206,206,206,206
5,696,696,696,696,696,696
6,177,177,177,177,177,177

In [28]:
test.sort_values(by='passenger_count', ascending=False)

,key,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count
9913,2015-01-18 14:06:23.0000006,2015-01-18 14:06:23 UTC,-73.988022,40.754070,-74.000282,40.759220,6
9781,2011-03-11 01:44:00.00000062,2011-03-11 01:44:00 UTC,-73.966473,40.764630,-73.850492,40.863917,6
9801,2014-04-27 02:57:00.000000144,2014-04-27 02:57:00 UTC,-73.983298,40.744197,-73.980452,40.760910,6
9800,2014-04-27 02:57:00.000000179,2014-04-27 02:57:00 UTC,-73.982872,40.727082,-73.953780,40.719530,6
9799,2014-04-27 02:57:00.000000183,2014-04-27 02:57:00 UTC,-74.008648,40.725952,-74.003053,40.719735,6
9798,2014-04-27 02:57:00.00000066,2014-04-27 02:57:00 UTC,-74.002670,40.734142,-73.916578,40.757800,6
9797,2014-04-27 02:57:00.000000173,2014-04-27 02:57:00 UTC,-73.994037,40.741442,-73.987442,40.759170,6
9796,2014-04-27 02:57:00.00000091,2014-04-27 02:57:00 UTC,-73.972880,40.685720,-74.000520,40.718390,6
9795,2014-04-27 02:57:00.000000166,2014-04-27 02:57:00 UTC,-74.003945,40.742037,-73.980700,40.775247,6
9794,2014-04-27 02:57:00.0000004,2014-04-27 02:57:00 UTC,-73.989067,40.731420,-73.998247,40.751782,6
9793,2014-04-27 02:57:00.000000178,2014-04-27 02:57:00 UTC,-74.002558,40.749942,-74.005525,40.740550,6
9792,2014-04-27 02:57:00.00000075,2014-04-27 02:57:00 UTC,-74.005278,40.739997,-73.976765,40.761340,6
9791,2014-04-27 02:57:00.00000078,2014-04-27 02:57:00 UTC,-73.995480,40.764640,-73.995310,40.759530,6
9790,2014-04-27 02:57:00.000000123,2014-04-27 02:57:00 UTC,-74.000865,40.736507,-73.991650,40.751505,6
9789,2015-04-11 20:31:32.0000004,2015-04-11 20:31:32 UTC,-73.991341,40.734180,-74.005348,40.739815,6
9788,2014-12-24 03:00:00.00000027,2014-12-24 03:00:00 UTC,-74.001568,40.722502,-74.015950,40.676607,6
9787,2014-12-24 03:00:00.0000002,2014-12-24 03:00:00 UTC,-73.995195,40.739627,-73.978082,40.778067,6
9786,2014-12-24 03:00:00.00000014,2014-12-24 03:00:00 UTC,-73.950440,40.775487,-73.949835,40.786237,6
9785,2014-12-24 03:00:00.0000003,2014-12-24 03:00:00 UTC,-73.988010,40.748140,-73.997560,40.741370,6
9784,2011-10-04 09:37:00.00000023,2011-10-04 09:37:00 UTC,-73.959473,40.771168,-73.976960,40.758607,6
9783,2011-10-04 09:37:00.000000102,2011-10-04 09:37:00 UTC,-74.003970,40.742985,-73.990020,40.765595,6
9802,2014-04-27 02:57:00.00000025,2014-04-27 02:57:00 UTC,-73.989563,40.726105,-73.924957,40.754342,6
9803,2014-04-27 02:57:00.00000052,2014-04-27 02:57:00 UTC,-73.989977,40.734412,-73.982510,40.723507,6
9804,2014-04-27 02:57:00.00000094,2014-04-27 02:57:00 UTC,-73.996220,40.725500,-73.995050,40.734667,6
9815,2011-12-13 22:00:00.000000221,2011-12-13 22:00:00 UTC,-73.987905,40.769712,-74.002462,40.744970,6
9823,2014-07-21 18:19:00.000000159,2014-07-21 18:19:00 UTC,-73.998758,40.745402,-73.995607,40.733278,6
9822,2014-07-21 18:19:00.000000153,2014-07-21 18:19:00 UTC,-73.999440,40.759220,-73.995980,40.759600,6
9821,2014-07-21 18:19:00.000000197,2014-07-21 18:19:00 UTC,-73.959852,40.773677,-73.952605,40.786290,6
9820,2015-02-26 15:55:48.0000001,2015-02-26 15:55:48 UTC,-74.013474,40.714226,-73.956177,40.726189,6
9819,2011-12-13 22:00:00.00000059,2011-12-13 22:00:00 UTC,-73.962820,40.763372,-73.973217,40.758532,6
...,...,...,...,...,...,...,...
3319,2012-11-20 21:54:00.000000178,2012-11-20 21:54:00 UTC,-73.982000,40.743302,-73.979480,40.781622,1
3320,2012-11-20 21:54:00.00000027,2012-11-20 21:54:00 UTC,-73.996632,40.723597,-73.969802,40.753002,1
3321,2012-11-20 21:54:00.000000176,2012-11-20 21:54:00 UTC,-73.977443,40.758462,-73.978385,40.754585,1
3322,2012-11-20 21:54:00.0000008,2012-11-20 21:54:00 UTC,-73.994203,40.714430,-73.980417,40.722390,1
3323,2012-11-20 21:54:00.00000061,2012-11-20 21:54:00 UTC,-73.957332,40.717635,-73.887405,40.718800,1
3324,2012-11-20 21:54:00.00000011,2012-11-20 21:54:00 UTC,-73.963257,40.758240,-73.986175,40.719492,1
3325,2012-11-20 21:54:00.00000096,2012-11-20 21:54:00 UTC,-73.972870,40.758640,-73.982498,40.770772,1
3326,2012-11-20 21:54:00.000000231,2012-11-20 21:54:00 UTC,-73.992507,40.694135,-74.000662,40.681507,1
3327,2012-11-20 21:54:00.000000190,2012-11-20 21:54:00 UTC,-73.967937,40.765608,-73.993128,40.729753,1
3328,2012-11-20 21:54:00.000000166,2012-11-20 21:54:00 UTC,-73.985058,40.749912,-74.039765,40.630427,1
3313,2012-11-20 21:54:00.0000003,2012-11-20 21:54:00 UTC,-74.002145,40.740395,-73.991787,40.754567,1
3311,2012-11-20 21:54:00.00000051,2012-11-20 21:54:00 UTC,-73.994305,40.690387,-73.995735,40.746007,1
3294,2012-11-20 21:54:00.000000126,2012-11-20 21:54:00 UTC,-73.971835,40.754947,-73.980400,40.765052,1
3310,2012-11-20 21:54:00.000000188,2012-11-20 21:54:00 UTC,-73.988738,40.763807,-73.980737,40.744915,1
3295,2012-11-20 21:54:00.00000099,2012-11-20 21:54:00 UTC,-73.960137,40.769670,-73.983807,40.733917,1
3296,2012-11-20 21:54:00.000000120,2012-11-20 21:54:00 UTC,-73.973262,40.764007,-73.969852,40.784612,1
3297,2012-11-20 21:54:00.0000009,2012-11-20 21:54:00 UTC,-73.967185,40.766407,-73.970273,40.761497,1
3298,2012-11-20 21:54:00.000000206,2012-11-20 21:54:00 UTC,-73.985602,40.753545,-73.971800,40.763062,1
3299,2012-11-20 21:54:00.00000079,2012-11-20 21:54:00 UTC,-73.964263,40.761420,-73.956980,40.775037,1
3300,2012-11-20 21:54:00.000000237,2012-11-20 21:54:00 UTC,-73.991557,40.759987,-74.003122,40.718887,1
3301,2012-11-20 21:54:00.000000143,2012-11-20 21:54:00 UTC,-73.995912,40.738717,-73.980000,40.782127,1
3302,2012-11-20 21:54:00.000000111,2012-11-20 21:54:00 UTC,-73.977685,40.753122,-73.987340,40.759295,1
3303,2012-11-20 21:54:00.000000106,2012-11-20 21:54:00 UTC,-73.982242,40.772947,-73.971137,40.751037,1
3304,2012-11-20 21:54:00.000000245,2012-11-20 21:54:00 UTC,-73.995532,40.725062,-73.988032,40.722677,1
3305,2012-11-20 21:54:00.00000032,2012-11-20 21:54:00 UTC,-73.978410,40.783063,-73.976500,40.751660,1
3306,2012-11-20 21:54:00.00000075,2012-11-20 21:54:00 UTC,-74.005805,40.725812,-73.997822,40.745012,1
3307,2012-11-20 21:54:00.000000244,2012-11-20 21:54:00 UTC,-74.009997,40.709302,-73.918428,40.749227,1
3308,2012-11-20 21:54:00.00000094,2012-11-20 21:54:00 UTC,-73.959715,40.780295,-73.955162,40.782592,1
3309,2012-11-20 21:54:00.000000118,2012-11-20 21:54:00 UTC,-73.953002,40.783090,-73.911592,40.903345,1
4957,2014-08-24 01:17:38.0000001,2014-08-24 01:17:38 UTC,-74.003854,40.741965,-74.002682,40.749948,1

In [30]:
data['Age'].isnull()

NameError: name 'data' is not defined