In [1]:
import numpy as np
import pandas as pd

## <font color = blue> 1. Object Creation

1. Series
2. DataFrame

In [3]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [4]:
dates = pd.date_range('20130101', periods = 6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [7]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
df

                   A         B         C         D
2013-01-01 -1.023613  0.393935 -0.386037 -1.100115
2013-01-02  1.233970 -1.360660 -1.608368 -0.251782
2013-01-03 -0.193924  0.025373 -0.358066  1.714073
2013-01-04  1.264135 -1.095767 -0.042344  0.133328
2013-01-05 -0.948979  0.393311 -1.139674  0.683289
2013-01-06 -1.192790  0.092425  0.482223 -0.415395

In [9]:
df2 = pd.DataFrame({'A': 1.,
                    'B': pd.Timestamp('20130102'),
                    'C': pd.Series(1, index=list(range(4)), dtype='float32'),
                    'D': np.array([3]*4, dtype='int32'),
                    'E': pd.Categorical(['test', 'train', 'test', 'train']),
                    'F':'foo'})
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [10]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

## <font color = blue> 2. Viewing Data

In [13]:
df.head()

                   A         B         C         D
2013-01-01 -1.023613  0.393935 -0.386037 -1.100115
2013-01-02  1.233970 -1.360660 -1.608368 -0.251782
2013-01-03 -0.193924  0.025373 -0.358066  1.714073
2013-01-04  1.264135 -1.095767 -0.042344  0.133328
2013-01-05 -0.948979  0.393311 -1.139674  0.683289

In [14]:
df.tail(3)

                   A         B         C         D
2013-01-04  1.264135 -1.095767 -0.042344  0.133328
2013-01-05 -0.948979  0.393311 -1.139674  0.683289
2013-01-06 -1.192790  0.092425  0.482223 -0.415395

In [15]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[ns]', freq='D')

In [17]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [18]:
df.to_numpy()

array([[-1.0236133 ,  0.39393476, -0.38603708, -1.10011531],
       [ 1.23396952, -1.36066042, -1.60836833, -0.25178247],
       [-0.19392377,  0.02537337, -0.35806638,  1.71407263],
       [ 1.26413493, -1.09576675, -0.0423443 ,  0.13332752],
       [-0.94897942,  0.39331097, -1.13967354,  0.68328903],
       [-1.19278969,  0.09242548,  0.48222348, -0.41539517]])

In [19]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.143534 -0.258564 -0.508711  0.127233
std    1.131884  0.770718  0.754261  0.976911
min   -1.192790 -1.360660 -1.608368 -1.100115
25%   -1.004955 -0.815482 -0.951264 -0.374492
50%   -0.571452  0.058899 -0.372052 -0.059227
75%    0.876996  0.318090 -0.121275  0.545799
max    1.264135  0.393935  0.482223  1.714073

In [20]:
df.T

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -1.023613    1.233970   -0.193924    1.264135   -0.948979   -1.192790
B    0.393935   -1.360660    0.025373   -1.095767    0.393311    0.092425
C   -0.386037   -1.608368   -0.358066   -0.042344   -1.139674    0.482223
D   -1.100115   -0.251782    1.714073    0.133328    0.683289   -0.415395

In [21]:
df.sort_index(axis=1, ascending=False)

                   D         C         B         A
2013-01-01 -1.100115 -0.386037  0.393935 -1.023613
2013-01-02 -0.251782 -1.608368 -1.360660  1.233970
2013-01-03  1.714073 -0.358066  0.025373 -0.193924
2013-01-04  0.133328 -0.042344 -1.095767  1.264135
2013-01-05  0.683289 -1.139674  0.393311 -0.948979
2013-01-06 -0.415395  0.482223  0.092425 -1.192790

In [22]:
df.sort_values(by='B')

                   A         B         C         D
2013-01-02  1.233970 -1.360660 -1.608368 -0.251782
2013-01-04  1.264135 -1.095767 -0.042344  0.133328
2013-01-03 -0.193924  0.025373 -0.358066  1.714073
2013-01-06 -1.192790  0.092425  0.482223 -0.415395
2013-01-05 -0.948979  0.393311 -1.139674  0.683289
2013-01-01 -1.023613  0.393935 -0.386037 -1.100115

## <font color = blue> 3. Selection

In [23]:
df['A']

2013-01-01   -1.023613
2013-01-02    1.233970
2013-01-03   -0.193924
2013-01-04    1.264135
2013-01-05   -0.948979
2013-01-06   -1.192790
Freq: D, Name: A, dtype: float64

In [24]:
df[0:3]

                   A         B         C         D
2013-01-01 -1.023613  0.393935 -0.386037 -1.100115
2013-01-02  1.233970 -1.360660 -1.608368 -0.251782
2013-01-03 -0.193924  0.025373 -0.358066  1.714073

In [26]:
df

                   A         B         C         D
2013-01-01 -1.023613  0.393935 -0.386037 -1.100115
2013-01-02  1.233970 -1.360660 -1.608368 -0.251782
2013-01-03 -0.193924  0.025373 -0.358066  1.714073
2013-01-04  1.264135 -1.095767 -0.042344  0.133328
2013-01-05 -0.948979  0.393311 -1.139674  0.683289
2013-01-06 -1.192790  0.092425  0.482223 -0.415395

In [27]:
df.loc[dates[0]]

A   -1.023613
B    0.393935
C   -0.386037
D   -1.100115
Name: 2013-01-01 00:00:00, dtype: float64

In [28]:
df.loc[:, ['A', 'B']]

                   A         B
2013-01-01 -1.023613  0.393935
2013-01-02  1.233970 -1.360660
2013-01-03 -0.193924  0.025373
2013-01-04  1.264135 -1.095767
2013-01-05 -0.948979  0.393311
2013-01-06 -1.192790  0.092425

In [29]:
df.loc[dates[0], 'A']

-1.0236132983345143

In [32]:
df.iloc[3]

A    1.264135
B   -1.095767
C   -0.042344
D    0.133328
Name: 2013-01-04 00:00:00, dtype: float64

In [33]:
df.iloc[3:5, 0:2]

                   A         B
2013-01-04  1.264135 -1.095767
2013-01-05 -0.948979  0.393311

In [34]:
df.iloc[1:3, :]

                   A         B         C         D
2013-01-02  1.233970 -1.360660 -1.608368 -0.251782
2013-01-03 -0.193924  0.025373 -0.358066  1.714073

In [35]:
df.iloc[1, 1]

-1.3606604154038973

In [36]:
df[df.A >0]

                   A         B         C         D
2013-01-02  1.233970 -1.360660 -1.608368 -0.251782
2013-01-04  1.264135 -1.095767 -0.042344  0.133328

In [37]:
df[df >0]

                   A         B         C         D
2013-01-01       NaN  0.393935       NaN       NaN
2013-01-02  1.233970       NaN       NaN       NaN
2013-01-03       NaN  0.025373       NaN  1.714073
2013-01-04  1.264135       NaN       NaN  0.133328
2013-01-05       NaN  0.393311       NaN  0.683289
2013-01-06       NaN  0.092425  0.482223       NaN

In [38]:
df2 = df.copy()
df2['E'] = ['one', 'one', 'two', 'three', 'four', 'three']

In [39]:
df2

                   A         B         C         D      E
2013-01-01 -1.023613  0.393935 -0.386037 -1.100115    one
2013-01-02  1.233970 -1.360660 -1.608368 -0.251782    one
2013-01-03 -0.193924  0.025373 -0.358066  1.714073    two
2013-01-04  1.264135 -1.095767 -0.042344  0.133328  three
2013-01-05 -0.948979  0.393311 -1.139674  0.683289   four
2013-01-06 -1.192790  0.092425  0.482223 -0.415395  three

In [40]:
s1 = pd.Series([1, 2, 3, 4, 5, 6], index=pd.date_range('20130102', periods=6))

In [41]:
s1

2013-01-02    1
2013-01-03    2
2013-01-04    3
2013-01-05    4
2013-01-06    5
2013-01-07    6
Freq: D, dtype: int64

In [42]:
df['F'] = s1

In [43]:
df

                   A         B         C         D    F
2013-01-01 -1.023613  0.393935 -0.386037 -1.100115  NaN
2013-01-02  1.233970 -1.360660 -1.608368 -0.251782  1.0
2013-01-03 -0.193924  0.025373 -0.358066  1.714073  2.0
2013-01-04  1.264135 -1.095767 -0.042344  0.133328  3.0
2013-01-05 -0.948979  0.393311 -1.139674  0.683289  4.0
2013-01-06 -1.192790  0.092425  0.482223 -0.415395  5.0

## <font color = blue> 4. Missing data

In [47]:
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ['E'])
df1.loc[dates[0]:dates[1], 'E'] = 1
df1

                   A         B         C         D    F    E
2013-01-01 -1.023613  0.393935 -0.386037 -1.100115  NaN  1.0
2013-01-02  1.233970 -1.360660 -1.608368 -0.251782  1.0  1.0
2013-01-03 -0.193924  0.025373 -0.358066  1.714073  2.0  NaN
2013-01-04  1.264135 -1.095767 -0.042344  0.133328  3.0  NaN

In [49]:
df1.dropna(how='any') # To drop rows that have missing data

                  A        B         C         D    F    E
2013-01-02  1.23397 -1.36066 -1.608368 -0.251782  1.0  1.0

In [51]:
df1.fillna(value=5) # Filling missing data

                   A         B         C         D    F    E
2013-01-01 -1.023613  0.393935 -0.386037 -1.100115  5.0  1.0
2013-01-02  1.233970 -1.360660 -1.608368 -0.251782  1.0  1.0
2013-01-03 -0.193924  0.025373 -0.358066  1.714073  2.0  5.0
2013-01-04  1.264135 -1.095767 -0.042344  0.133328  3.0  5.0

## <font color = blue> 5. Operations

In [52]:
df.mean()

A   -0.143534
B   -0.258564
C   -0.508711
D    0.127233
F    3.000000
dtype: float64

In [57]:
df.mean(1)

2013-01-01   -0.528958
2013-01-02   -0.197368
2013-01-03    0.637491
2013-01-04    0.651870
2013-01-05    0.597589
2013-01-06    0.793293
Freq: D, dtype: float64

In [58]:
s = pd.Series([1, 3, 5, np.nan, 6, 8], index=dates).shift(2)
s

2013-01-01    NaN
2013-01-02    NaN
2013-01-03    1.0
2013-01-04    3.0
2013-01-05    5.0
2013-01-06    NaN
Freq: D, dtype: float64

In [59]:
df.sub(s, axis='index')

                   A         B         C         D    F
2013-01-01       NaN       NaN       NaN       NaN  NaN
2013-01-02       NaN       NaN       NaN       NaN  NaN
2013-01-03 -1.193924 -0.974627 -1.358066  0.714073  1.0
2013-01-04 -1.735865 -4.095767 -3.042344 -2.866672  0.0
2013-01-05 -5.948979 -4.606689 -6.139674 -4.316711 -1.0
2013-01-06       NaN       NaN       NaN       NaN  NaN

In [60]:
df.apply(np.cumsum)

                   A         B         C         D     F
2013-01-01 -1.023613  0.393935 -0.386037 -1.100115   NaN
2013-01-02  0.210356 -0.966726 -1.994405 -1.351898   1.0
2013-01-03  0.016432 -0.941352 -2.352472  0.362175   3.0
2013-01-04  1.280567 -2.037119 -2.394816  0.495502   6.0
2013-01-05  0.331588 -1.643808 -3.534490  1.178791  10.0
2013-01-06 -0.861202 -1.551383 -3.052266  0.763396  15.0

In [61]:
df.apply(lambda x: x.max() - x.min())

A    2.456925
B    1.754595
C    2.090592
D    2.814188
F    4.000000
dtype: float64

In [63]:
s = pd.Series(np.random.randint(0, 7, size=10))
s

0    0
1    5
2    5
3    0
4    6
5    0
6    4
7    0
8    6
9    2
dtype: int64

In [64]:
s.value_counts()

0    4
6    2
5    2
4    1
2    1
dtype: int64

In [65]:
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

## <font color = blue> 6. Merge

In [66]:
df = pd.DataFrame(np.random.randn(10,4))

In [67]:
df

          0         1         2         3
0 -0.893846  0.698698 -2.456548 -1.928336
1 -0.475446  0.022200  1.544622  0.650270
2 -0.752129 -0.725902 -0.618817  0.318509
3 -1.113442 -0.064715 -1.178707  1.222517
4 -0.807740 -0.401282 -0.446841 -0.748474
5  1.781507 -1.973110  0.688160 -0.517388
6  1.773884  0.149265  0.173006 -1.475050
7 -0.671816  0.023763 -0.118179  0.128642
8  0.835606 -0.202813 -1.275492 -0.061632
9 -0.218574 -1.439947  0.613029 -0.174964

In [72]:
pieces = [df[:2], df[7:], df[7:]]

In [73]:
pd.concat(pieces)

          0         1         2         3
0 -0.893846  0.698698 -2.456548 -1.928336
1 -0.475446  0.022200  1.544622  0.650270
7 -0.671816  0.023763 -0.118179  0.128642
8  0.835606 -0.202813 -1.275492 -0.061632
9 -0.218574 -1.439947  0.613029 -0.174964
7 -0.671816  0.023763 -0.118179  0.128642
8  0.835606 -0.202813 -1.275492 -0.061632
9 -0.218574 -1.439947  0.613029 -0.174964

In [74]:
left = pd.DataFrame({'key':['foo', 'foo'], 'lval':[1,2]})
right = pd.DataFrame({'key':['foo', 'foo'], 'rval':[4,5]})

In [75]:
left

   key  lval
0  foo     1
1  foo     2

In [76]:
right

   key  rval
0  foo     4
1  foo     5

In [79]:
pd.merge(left, right, on ='key')

   key  lval  rval
0  foo     1     4
1  foo     1     5
2  foo     2     4
3  foo     2     5

## <font color='blue'> 7. Grouping

In [85]:
df = pd.DataFrame({'A': ['foo', 'bar', 'foo', 'bar','foo', 'bar', 'foo', 'foo'],
                   'B': ['one', 'one', 'two', 'three','two', 'two', 'one', 'three'],
                   'C': np.random.randn(8),
                   'D': np.random.randn(8)})
df

     A      B         C         D
0  foo    one -1.111263 -0.599258
1  bar    one  1.229194 -0.854477
2  foo    two  0.981656 -0.960466
3  bar  three  0.350613  0.133246
4  foo    two  0.630152 -0.743745
5  bar    two  0.776113 -1.037581
6  foo    one  1.105124 -2.239009
7  foo  three  0.257651 -0.238929

In [87]:
df.groupby(['A']).sum()

            C         D
A
bar  2.355919 -1.758812
foo  1.863320 -4.781407

In [88]:
df.groupby(['A','B']).sum()

                  C         D
A   B
bar one    1.229194 -0.854477
    three  0.350613  0.133246
    two    0.776113 -1.037581
foo one   -0.006139 -2.838267
    three  0.257651 -0.238929
    two    1.611808 -1.704212

## <font color='blue'> 8. Reshaping

In [95]:
tuples = list(zip(*[['bar', 'bar', 'baz', 'baz'
                     'foo', 'foo', 'qux', 'qux'],
                    ['one', 'two', 'one', 'two',
                  'one', 'two', 'one', 'two']])) 

index = pd.MultiIndex.from_tuples(tuples, names=['first', 'second'])
df = pd.DataFrame(np.random.randn(7, 2), index=index, columns=['A', 'B'])
df2 = df[:4]
df2

                      A         B
first  second
bar    one     0.404296  1.562633
       two     0.228183  1.165786
baz    one     0.376206  0.583340
bazfoo two     0.748087  0.979917

In [96]:
stacked = df2.stack()
stacked

first   second
bar     one     A    0.404296
                B    1.562633
        two     A    0.228183
                B    1.165786
baz     one     A    0.376206
                B    0.583340
bazfoo  two     A    0.748087
                B    0.979917
dtype: float64

In [97]:
stacked.unstack()

                      A         B
first  second
bar    one     0.404296  1.562633
       two     0.228183  1.165786
baz    one     0.376206  0.583340
bazfoo two     0.748087  0.979917

## <font color='blue'> 9. Getting data in/out

In [98]:
df.to_csv('foo.csv')

In [100]:
pd.read_csv('foo.csv')

    first second         A         B
0     bar    one  0.404296  1.562633
1     bar    two  0.228183  1.165786
2     baz    one  0.376206  0.583340
3  bazfoo    two  0.748087  0.979917
4     foo    one -0.871284  0.513284
5     qux    two  1.575588  0.512777
6     qux    one -3.331210 -0.855678