In [6]:
import pandas as pd
import os
import glob

In [7]:
path = os.getcwd()
path

'/Users/jooyoungson/TIL/Archive_2019/Study_DataScience/1_DataAnalysis/02_Pandas'

In [19]:
data_path = os.path.join(path + '/doit_pandas-master/data')

In [23]:
data_path

'/Users/jooyoungson/TIL/Archive_2019/Study_DataScience/1_DataAnalysis/02_Pandas/doit_pandas-master/data'

In [25]:
df = pd.read_csv(data_path+'/gapminder.tsv', sep='\t')

In [26]:
type(df)

pandas.core.frame.DataFrame

In [27]:
df.shape

(1704, 6)

In [28]:
df.columns

Index(['country', 'continent', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='object')

In [29]:
df.dtypes

country       object
continent     object
year           int64
lifeExp      float64
pop            int64
gdpPercap    float64
dtype: object

## 02-2 데이터 추출하기

In [31]:
country_df = df['country']
print(type(country_df))

<class 'pandas.core.series.Series'>

In [36]:
country_df.head()

0    Afghanistan
1    Afghanistan
2    Afghanistan
3    Afghanistan
4    Afghanistan
Name: country, dtype: object

In [38]:
subset = df[['country','continent','year']]

In [39]:
print(type(subset))

<class 'pandas.core.frame.DataFrame'>

In [40]:
subset.head()

       country continent  year
0  Afghanistan      Asia  1952
1  Afghanistan      Asia  1957
2  Afghanistan      Asia  1962
3  Afghanistan      Asia  1967
4  Afghanistan      Asia  1972

In [43]:
df.head()

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

In [41]:
df.loc[0]

country      Afghanistan
continent           Asia
year                1952
lifeExp           28.801
pop              8425333
gdpPercap        779.445
Name: 0, dtype: object

In [42]:
df.loc[99]

country      Bangladesh
continent          Asia
year               1967
lifeExp          43.453
pop            62821884
gdpPercap       721.186
Name: 99, dtype: object

In [44]:
number_of_rows = df.shape[0]
last_row_index = number_of_rows - 1

In [45]:
df.loc[last_row_index]

country      Zimbabwe
continent      Africa
year             2007
lifeExp        43.487
pop          12311143
gdpPercap     469.709
Name: 1703, dtype: object

In [49]:
subset_loc = df.loc[1]

In [50]:
subset_loc

country      Afghanistan
continent           Asia
year                1957
lifeExp           30.332
pop              9240934
gdpPercap        820.853
Name: 1, dtype: object

In [51]:
df.iloc[1]

country      Afghanistan
continent           Asia
year                1957
lifeExp           30.332
pop              9240934
gdpPercap        820.853
Name: 1, dtype: object

In [53]:
df.iloc[[0, 99, 999]]

         country continent  year  lifeExp       pop    gdpPercap
0    Afghanistan      Asia  1952   28.801   8425333   779.445314
99    Bangladesh      Asia  1967   43.453  62821884   721.186086
999     Mongolia      Asia  1967   51.253   1149500  1226.041130

In [54]:
df.loc[[0, 99, 999]]

         country continent  year  lifeExp       pop    gdpPercap
0    Afghanistan      Asia  1952   28.801   8425333   779.445314
99    Bangladesh      Asia  1967   43.453  62821884   721.186086
999     Mongolia      Asia  1967   51.253   1149500  1226.041130

In [55]:
subset = df.loc[:,['year','pop']]
subset.head()

   year       pop
0  1952   8425333
1  1957   9240934
2  1962  10267083
3  1967  11537966
4  1972  13079460

In [56]:
subset = df.iloc[:,[2,4,-1]]
subset.head()

   year       pop   gdpPercap
0  1952   8425333  779.445314
1  1957   9240934  820.853030
2  1962  10267083  853.100710
3  1967  11537966  836.197138
4  1972  13079460  739.981106

In [57]:
df.head(n=10)

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106
5  Afghanistan      Asia  1977   38.438  14880372  786.113360
6  Afghanistan      Asia  1982   39.854  12881816  978.011439
7  Afghanistan      Asia  1987   40.822  13867957  852.395945
8  Afghanistan      Asia  1992   41.674  16317921  649.341395
9  Afghanistan      Asia  1997   41.763  22227415  635.341351

In [58]:
#연도별 평균을 구하고 싶다면, 데이터를 year열로 그룹화 하고 lifeExp열의 평균을 구한다. 
df.groupby('year')['lifeExp'].mean()

year
1952    49.057620
1957    51.507401
1962    53.609249
1967    55.678290
1972    57.647386
1977    59.570157
1982    61.533197
1987    63.212613
1992    64.160338
1997    65.014676
2002    65.694923
2007    67.007423
Name: lifeExp, dtype: float64

In [59]:
df.groupby('year')

In [60]:
a = df.groupby('year')

In [63]:
a['lifeExp'].mean()

year
1952    49.057620
1957    51.507401
1962    53.609249
1967    55.678290
1972    57.647386
1977    59.570157
1982    61.533197
1987    63.212613
1992    64.160338
1997    65.014676
2002    65.694923
2007    67.007423
Name: lifeExp, dtype: float64

In [64]:
df.groupby('continent')['country'].nunique()

continent
Africa      52
Americas    25
Asia        33
Europe      30
Oceania      2
Name: country, dtype: int64

In [70]:
df = pd.read_csv(data_path+'/scientists.csv')
df.head()

                   Name        Born        Died  Age    Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16   37       Chemist
1        William Gosset  1876-06-13  1937-10-16   61  Statistician
2  Florence Nightingale  1820-05-12  1910-08-13   90         Nurse
3           Marie Curie  1867-11-07  1934-07-04   66       Chemist
4         Rachel Carson  1907-05-27  1964-04-14   56     Biologist

In [67]:
df_dropped = df.drop(['Age'], axis=1)

In [69]:
df_dropped.head()

                   Name        Born        Died    Occupation
0     Rosaline Franklin  1920-07-25  1958-04-16       Chemist
1        William Gosset  1876-06-13  1937-10-16  Statistician
2  Florence Nightingale  1820-05-12  1910-08-13         Nurse
3           Marie Curie  1867-11-07  1934-07-04       Chemist
4         Rachel Carson  1907-05-27  1964-04-14     Biologist