# Pandas시작하기


pandas는 앞으로 가장자주 살펴볼 라이브러리다. pandas는 고수준의 자료 구조와 파이썬을 통한 빠르고 쉬운 데이터 분석 도구를 포함한다. pandas는 Numpy기반에서 개발되어 Numpy를 사용하는 애플리케이션에서 쉽게 사용할 수 있다. 

나는 투자 운용 회사인 AQR에 재직 중이던 2008년 초에 pandas를 개발하기 시작했다. 그때는 내가 원하는 명확한 요구사항에 부합하는 도구를 찾을 수 없어 안타까웠는데, 내가 원하는 기능은 다음과 같다. 

- 자동적으로 혹은 명시적으로 축의 이름에 따라 데이터를 정렬할 수 있는 자료구조. 잘못 정렬된 데이터에 의한 일반적인 오류를 예방하고 다양한 소스에서 가져온 다양한 방식으로 색인되어 있는 데이터를 다룰 수 있는 기능.
- 통합된 시계열 기능
- 시계열 데이터와 비시계열 데이터를 함께 다룰 수 있는 통합 자료 구조
- 산술연산과 한 축의 모든 값을 더하는 등의 데이터 축약연산은 축의 이름 같은 메타데이터로 전달될 수 있어야 함. 
- 누락된 데이터를 유연하게 처리할 수 있는 기능
- SQL같은 일반 데이터베이스처럼 데이터를 합치고 관계연산을 수행하는 기능. 

나는 가급적이면 한 가지 언어로 범용 소프트웨어를 쉽게 개발할 수 있도록 이 모든 기능을 한번에 해결할 수 있기를 원했다. 파이썬은 이를 위한 훌륭한 후보였지만 그 당시에는 이 기능을 지원하는 도구와 자료 구조가 없었다. 

지난 4년간 pandas는 내가 기대했던 것보다 훨씬 더 안정적으로 대용량 데이터를 처리할 수 있게 확장되었고 상당히 큰 라이브러리가 되었음에도 다행히 초기에 내가 원했던 간편함과 단숨함에 대한 기본 방침은 유지되었다. 이 책을 읽고 난 후 독자에게도 pandas가 없어서는 안될 필수 도구가 되기를 바란다.

In [3]:
import pandas as pd
#from pandas import Series, DataFrame
import numpy as np

In [7]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [8]:
obj.values

array([ 4,  7, -5,  3])

In [9]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [11]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [14]:
obj2['a']

-5

In [15]:
obj2['d'] = 6

In [16]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [17]:
obj2[obj2 > 0]
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [18]:
'b' in obj2

True

In [19]:
'e' in obj2

False

In [30]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)

In [31]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

이 예제를 보면 sdata에 있는 값 중 3개만 확인할 수 있는데, 이는 'California'에 대한 값을 찾을 수 없기 때문이다.

### <font color='skyblue'> NaN(Not a Number) 누락된 값 혹은 NA값으로 취급한다. </font>

In [43]:
obj4.isnull()
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [44]:
obj4.notnull()
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [37]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [38]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [29]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [48]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year' : [2000, 2001, 2002, 2001, 2002],
        'pop' : [1.5, 1.7, 3.6, 2.4, 2.9]
       }
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four', 'five'])

In [49]:
frame2

       year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [50]:
frame2.ix['three']

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [51]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [52]:
pop = {'Nevada': {2001: 2.4, 2002:2.9}, 'Ohio': {2000: 1.5, 2001:1.7, 2002:3.6}}

In [53]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [54]:
pop['Nevada']

{2001: 2.4, 2002: 2.9}

In [55]:
frame3 = pd.DataFrame(pop)

In [56]:
frame3

      Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [58]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index